package mybatis.dao;

import java.util.List;
import mybatis.model.Bill;
import mybatis.model.BillExample;
import org.apache.ibatis.annotations.Param;

public interface BillMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int countByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int deleteByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int deleteByPrimaryKey(Integer billId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int insert(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int insertSelective(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	List<Bill> selectByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	Bill selectByPrimaryKey(Integer billId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Bill record,
			@Param("example") BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByExample(@Param("record") Bill record,
			@Param("example") BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByPrimaryKeySelective(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByPrimaryKey(Bill record);
}