package mybatis.dao;

import java.util.List;
import mybatis.model.BillDetail;
import mybatis.model.BillDetailExample;
import org.apache.ibatis.annotations.Param;

public interface BillDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    int countByExample(BillDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    int deleteByExample(BillDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    int deleteByPrimaryKey(Integer billDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    int insert(BillDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    int insertSelective(BillDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    List<BillDetail> selectByExample(BillDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    BillDetail selectByPrimaryKey(Integer billDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") BillDetail record, @Param("example") BillDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    int updateByExample(@Param("record") BillDetail record, @Param("example") BillDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    int updateByPrimaryKeySelective(BillDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detail
     *
     * @mbggenerated Mon May 18 20:23:20 CST 2015
     */
    int updateByPrimaryKey(BillDetail record);
    
    List<BillDetail> selectByBillId(@Param("billId")Integer billId);
}