package mybatis.dao;

import java.util.List;
import mybatis.model.BillConf;
import mybatis.model.BillConfExample;
import org.apache.ibatis.annotations.Param;

public interface BillConfMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int countByExample(BillConfExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int deleteByExample(BillConfExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int deleteByPrimaryKey(Integer billItemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int insert(BillConf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int insertSelective(BillConf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	List<BillConf> selectByExample(BillConfExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	BillConf selectByPrimaryKey(Integer billItemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByExampleSelective(@Param("record") BillConf record,
			@Param("example") BillConfExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByExample(@Param("record") BillConf record,
			@Param("example") BillConfExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByPrimaryKeySelective(BillConf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByPrimaryKey(BillConf record);
}