package mybatis.dao;

import java.util.List;
import mybatis.model.Cust;
import mybatis.model.CustExample;
import org.apache.ibatis.annotations.Param;

public interface CustMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int countByExample(CustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int deleteByExample(CustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int deleteByPrimaryKey(Integer custId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int insert(Cust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int insertSelective(Cust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	List<Cust> selectByExample(CustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	Cust selectByPrimaryKey(Integer custId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Cust record,
			@Param("example") CustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByExample(@Param("record") Cust record,
			@Param("example") CustExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByPrimaryKeySelective(Cust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByPrimaryKey(Cust record);
}