package mybatis.dao;

import java.util.List;

import mybatis.model.Prod;
import mybatis.model.ProdExample;

import org.apache.ibatis.annotations.Param;

public interface ProdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int countByExample(ProdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int deleteByExample(ProdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int deleteByPrimaryKey(Integer prodId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int insert(Prod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int insertSelective(Prod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	List<Prod> selectByExample(ProdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	Prod selectByPrimaryKey(Integer prodId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Prod record,
			@Param("example") ProdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByExample(@Param("record") Prod record,
			@Param("example") ProdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByPrimaryKeySelective(Prod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	int updateByPrimaryKey(Prod record);
	
	/**
	 * 
	 * @param key 客户证件号码或者产品的接入号码
	 * @return 返回产品列表
	 */
	List<Prod> selectByKey(@Param("key")String key);
	
	public Prod selectByProdIdAndBillMonths(@Param("prodId")String prodId,@Param("billMonths")String[] billMonths);
	
}