/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package action;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts2.ServletActionContext;

import mybatis.dao.ProdMapper;
import mybatis.model.Prod;

import com.opensymphony.xwork2.ActionSupport;

/**
 * MyEclipse Struts Creation date: 06-29-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/login" name="loginForm" input="/form/login.jsp"
 *                scope="request" validate="true"
 */
public class BillManageAction extends ActionSupport {
	/*
	 * Generated Methods
	 */
	private ProdMapper prodMapper;
	private Map responseJson;

	public Map getResponseJson() {
		return responseJson;
	}

	public void setResponseJson(Map responseJson) {
		this.responseJson = responseJson;
	}

	public ProdMapper getProdMapper() {
		return prodMapper;
	}

	public void setProdMapper(ProdMapper prodMapper) {
		this.prodMapper = prodMapper;
	}

	private String searchKey;

	public String getSearchKey() {
		return searchKey;
	}

	public void setSearchKey(String searchKey) {
		this.searchKey = searchKey;
	}

	public String getProdsByKey() {

		System.out.println(searchKey);
		List<Prod> prodList = prodMapper.selectByKey(searchKey);
		Map returned = new HashMap();
		returned.put("prodList", prodList);
		this.setResponseJson(returned);
		return SUCCESS;

	}

	private String selectedProdId;
	private String billMonth;

	public String getBillMonth() {
		return billMonth;
	}

	public void setBillMonth(String billMonth) {
		this.billMonth = billMonth;
	}

	public String getSelectedProdId() {
		return selectedProdId;
	}

	public void setSelectedProdId(String selectedProdId) {
		this.selectedProdId = selectedProdId;
	}

	public String showProd() {
		Map session = ServletActionContext.getContext().getSession();
		HttpServletRequest request = ServletActionContext.getRequest();
		String[] billMonthArray;
		if (billMonth == null||billMonth.trim().equals("")) {
			 // 取前三个月
				billMonthArray=new String[]{getMonth(-1),getMonth(-2),getMonth(-3)};
			}
		else{
		
			billMonthArray=new String[]{billMonth};
		}
		Prod prod = prodMapper.selectByProdIdAndBillMonths(selectedProdId, billMonthArray);
		
		//prod有可能是NULL
		//System.out.println(prod.getProdId() + ":" + prod.getProdNumber());
		request.setAttribute("currentProd", prod);
		if(searchKey!=null)
		request.setAttribute("searchKey", searchKey);
		if(billMonth != null&&!billMonth.trim().equals(""))
		request.setAttribute("billMonth", billMonth);
		ServletActionContext.setRequest(ServletActionContext.getRequest());
		return "success";
	}

	public static String getMonth(int ref) {
		Calendar rightNow = Calendar.getInstance();
		SimpleDateFormat fmt = new SimpleDateFormat("yyyyMM");
		rightNow.add(Calendar.MONTH, ref);

		// 格式大小写有区别
		String sysDatetime = fmt.format(rightNow.getTime());
		return sysDatetime;
	}
	
	

}