package mybatis.model;

public class Bill {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.bill_id
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private Integer billId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.prod_id
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private Integer prodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.bill_month
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private String billMonth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.bill_amount
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private Double billAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.bill_own_amount
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private Double billOwnAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.bill_prepay_amount
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private Double billPrepayAmount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.bill_id
	 * @return  the value of bill.bill_id
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Integer getBillId() {
		return billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.bill_id
	 * @param billId  the value for bill.bill_id
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.prod_id
	 * @return  the value of bill.prod_id
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Integer getProdId() {
		return prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.prod_id
	 * @param prodId  the value for bill.prod_id
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setProdId(Integer prodId) {
		this.prodId = prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.bill_month
	 * @return  the value of bill.bill_month
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public String getBillMonth() {
		return billMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.bill_month
	 * @param billMonth  the value for bill.bill_month
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setBillMonth(String billMonth) {
		this.billMonth = billMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.bill_amount
	 * @return  the value of bill.bill_amount
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Double getBillAmount() {
		return billAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.bill_amount
	 * @param billAmount  the value for bill.bill_amount
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setBillAmount(Double billAmount) {
		this.billAmount = billAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.bill_own_amount
	 * @return  the value of bill.bill_own_amount
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Double getBillOwnAmount() {
		return billOwnAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.bill_own_amount
	 * @param billOwnAmount  the value for bill.bill_own_amount
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setBillOwnAmount(Double billOwnAmount) {
		this.billOwnAmount = billOwnAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.bill_prepay_amount
	 * @return  the value of bill.bill_prepay_amount
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Double getBillPrepayAmount() {
		return billPrepayAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.bill_prepay_amount
	 * @param billPrepayAmount  the value for bill.bill_prepay_amount
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setBillPrepayAmount(Double billPrepayAmount) {
		this.billPrepayAmount = billPrepayAmount;
	}
}