package mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class BillConfExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public BillConfExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBillItemIdIsNull() {
			addCriterion("bill_item_id is null");
			return (Criteria) this;
		}

		public Criteria andBillItemIdIsNotNull() {
			addCriterion("bill_item_id is not null");
			return (Criteria) this;
		}

		public Criteria andBillItemIdEqualTo(Integer value) {
			addCriterion("bill_item_id =", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdNotEqualTo(Integer value) {
			addCriterion("bill_item_id <>", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdGreaterThan(Integer value) {
			addCriterion("bill_item_id >", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("bill_item_id >=", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdLessThan(Integer value) {
			addCriterion("bill_item_id <", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdLessThanOrEqualTo(Integer value) {
			addCriterion("bill_item_id <=", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdIn(List<Integer> values) {
			addCriterion("bill_item_id in", values, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdNotIn(List<Integer> values) {
			addCriterion("bill_item_id not in", values, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdBetween(Integer value1, Integer value2) {
			addCriterion("bill_item_id between", value1, value2, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdNotBetween(Integer value1, Integer value2) {
			addCriterion("bill_item_id not between", value1, value2,
					"billItemId");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdIsNull() {
			addCriterion("parent_bill_item_id is null");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdIsNotNull() {
			addCriterion("parent_bill_item_id is not null");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdEqualTo(Integer value) {
			addCriterion("parent_bill_item_id =", value, "parentBillItemId");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdNotEqualTo(Integer value) {
			addCriterion("parent_bill_item_id <>", value, "parentBillItemId");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdGreaterThan(Integer value) {
			addCriterion("parent_bill_item_id >", value, "parentBillItemId");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("parent_bill_item_id >=", value, "parentBillItemId");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdLessThan(Integer value) {
			addCriterion("parent_bill_item_id <", value, "parentBillItemId");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdLessThanOrEqualTo(Integer value) {
			addCriterion("parent_bill_item_id <=", value, "parentBillItemId");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdIn(List<Integer> values) {
			addCriterion("parent_bill_item_id in", values, "parentBillItemId");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdNotIn(List<Integer> values) {
			addCriterion("parent_bill_item_id not in", values,
					"parentBillItemId");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdBetween(Integer value1,
				Integer value2) {
			addCriterion("parent_bill_item_id between", value1, value2,
					"parentBillItemId");
			return (Criteria) this;
		}

		public Criteria andParentBillItemIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("parent_bill_item_id not between", value1, value2,
					"parentBillItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemNameIsNull() {
			addCriterion("bill_item_name is null");
			return (Criteria) this;
		}

		public Criteria andBillItemNameIsNotNull() {
			addCriterion("bill_item_name is not null");
			return (Criteria) this;
		}

		public Criteria andBillItemNameEqualTo(String value) {
			addCriterion("bill_item_name =", value, "billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameNotEqualTo(String value) {
			addCriterion("bill_item_name <>", value, "billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameGreaterThan(String value) {
			addCriterion("bill_item_name >", value, "billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameGreaterThanOrEqualTo(String value) {
			addCriterion("bill_item_name >=", value, "billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameLessThan(String value) {
			addCriterion("bill_item_name <", value, "billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameLessThanOrEqualTo(String value) {
			addCriterion("bill_item_name <=", value, "billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameLike(String value) {
			addCriterion("bill_item_name like", value, "billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameNotLike(String value) {
			addCriterion("bill_item_name not like", value, "billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameIn(List<String> values) {
			addCriterion("bill_item_name in", values, "billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameNotIn(List<String> values) {
			addCriterion("bill_item_name not in", values, "billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameBetween(String value1, String value2) {
			addCriterion("bill_item_name between", value1, value2,
					"billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemNameNotBetween(String value1, String value2) {
			addCriterion("bill_item_name not between", value1, value2,
					"billItemName");
			return (Criteria) this;
		}

		public Criteria andBillItemDwIsNull() {
			addCriterion("bill_item_dw is null");
			return (Criteria) this;
		}

		public Criteria andBillItemDwIsNotNull() {
			addCriterion("bill_item_dw is not null");
			return (Criteria) this;
		}

		public Criteria andBillItemDwEqualTo(String value) {
			addCriterion("bill_item_dw =", value, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwNotEqualTo(String value) {
			addCriterion("bill_item_dw <>", value, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwGreaterThan(String value) {
			addCriterion("bill_item_dw >", value, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwGreaterThanOrEqualTo(String value) {
			addCriterion("bill_item_dw >=", value, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwLessThan(String value) {
			addCriterion("bill_item_dw <", value, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwLessThanOrEqualTo(String value) {
			addCriterion("bill_item_dw <=", value, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwLike(String value) {
			addCriterion("bill_item_dw like", value, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwNotLike(String value) {
			addCriterion("bill_item_dw not like", value, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwIn(List<String> values) {
			addCriterion("bill_item_dw in", values, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwNotIn(List<String> values) {
			addCriterion("bill_item_dw not in", values, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwBetween(String value1, String value2) {
			addCriterion("bill_item_dw between", value1, value2, "billItemDw");
			return (Criteria) this;
		}

		public Criteria andBillItemDwNotBetween(String value1, String value2) {
			addCriterion("bill_item_dw not between", value1, value2,
					"billItemDw");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bill_conf
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill_conf
     *
     * @mbggenerated do_not_delete_during_merge Mon May 18 19:22:03 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}