package mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class BillDetailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public BillDetailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBillDetailIdIsNull() {
			addCriterion("bill_detail_id is null");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdIsNotNull() {
			addCriterion("bill_detail_id is not null");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdEqualTo(Integer value) {
			addCriterion("bill_detail_id =", value, "billDetailId");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdNotEqualTo(Integer value) {
			addCriterion("bill_detail_id <>", value, "billDetailId");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdGreaterThan(Integer value) {
			addCriterion("bill_detail_id >", value, "billDetailId");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("bill_detail_id >=", value, "billDetailId");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdLessThan(Integer value) {
			addCriterion("bill_detail_id <", value, "billDetailId");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdLessThanOrEqualTo(Integer value) {
			addCriterion("bill_detail_id <=", value, "billDetailId");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdIn(List<Integer> values) {
			addCriterion("bill_detail_id in", values, "billDetailId");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdNotIn(List<Integer> values) {
			addCriterion("bill_detail_id not in", values, "billDetailId");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdBetween(Integer value1, Integer value2) {
			addCriterion("bill_detail_id between", value1, value2,
					"billDetailId");
			return (Criteria) this;
		}

		public Criteria andBillDetailIdNotBetween(Integer value1, Integer value2) {
			addCriterion("bill_detail_id not between", value1, value2,
					"billDetailId");
			return (Criteria) this;
		}

		public Criteria andBillIdIsNull() {
			addCriterion("bill_id is null");
			return (Criteria) this;
		}

		public Criteria andBillIdIsNotNull() {
			addCriterion("bill_id is not null");
			return (Criteria) this;
		}

		public Criteria andBillIdEqualTo(Integer value) {
			addCriterion("bill_id =", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdNotEqualTo(Integer value) {
			addCriterion("bill_id <>", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdGreaterThan(Integer value) {
			addCriterion("bill_id >", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("bill_id >=", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdLessThan(Integer value) {
			addCriterion("bill_id <", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdLessThanOrEqualTo(Integer value) {
			addCriterion("bill_id <=", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdIn(List<Integer> values) {
			addCriterion("bill_id in", values, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdNotIn(List<Integer> values) {
			addCriterion("bill_id not in", values, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdBetween(Integer value1, Integer value2) {
			addCriterion("bill_id between", value1, value2, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdNotBetween(Integer value1, Integer value2) {
			addCriterion("bill_id not between", value1, value2, "billId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdIsNull() {
			addCriterion("\" bill_item_id\" is null");
			return (Criteria) this;
		}

		public Criteria andBillItemIdIsNotNull() {
			addCriterion("\" bill_item_id\" is not null");
			return (Criteria) this;
		}

		public Criteria andBillItemIdEqualTo(Integer value) {
			addCriterion("\" bill_item_id\" =", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdNotEqualTo(Integer value) {
			addCriterion("\" bill_item_id\" <>", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdGreaterThan(Integer value) {
			addCriterion("\" bill_item_id\" >", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("\" bill_item_id\" >=", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdLessThan(Integer value) {
			addCriterion("\" bill_item_id\" <", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdLessThanOrEqualTo(Integer value) {
			addCriterion("\" bill_item_id\" <=", value, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdIn(List<Integer> values) {
			addCriterion("\" bill_item_id\" in", values, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdNotIn(List<Integer> values) {
			addCriterion("\" bill_item_id\" not in", values, "billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdBetween(Integer value1, Integer value2) {
			addCriterion("\" bill_item_id\" between", value1, value2,
					"billItemId");
			return (Criteria) this;
		}

		public Criteria andBillItemIdNotBetween(Integer value1, Integer value2) {
			addCriterion("\" bill_item_id\" not between", value1, value2,
					"billItemId");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(Double value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(Double value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(Double value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(Double value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(Double value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(Double value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<Double> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<Double> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(Double value1, Double value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(Double value1, Double value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bill_detail
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill_detail
     *
     * @mbggenerated do_not_delete_during_merge Mon May 18 19:22:03 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}