package mybatis.model;

import java.util.Date;

public class Cust {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_id
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private Integer custId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_name
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private String custName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_card
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private String custCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_user_name
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private String custUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_user_address
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private String custUserAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_user_phone
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private String custUserPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.cust_date
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	private Date custDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_id
	 * @return  the value of cust.cust_id
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Integer getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_id
	 * @param custId  the value for cust.cust_id
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_name
	 * @return  the value of cust.cust_name
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public String getCustName() {
		return custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_name
	 * @param custName  the value for cust.cust_name
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setCustName(String custName) {
		this.custName = custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_card
	 * @return  the value of cust.cust_card
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public String getCustCard() {
		return custCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_card
	 * @param custCard  the value for cust.cust_card
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setCustCard(String custCard) {
		this.custCard = custCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_user_name
	 * @return  the value of cust.cust_user_name
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public String getCustUserName() {
		return custUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_user_name
	 * @param custUserName  the value for cust.cust_user_name
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setCustUserName(String custUserName) {
		this.custUserName = custUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_user_address
	 * @return  the value of cust.cust_user_address
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public String getCustUserAddress() {
		return custUserAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_user_address
	 * @param custUserAddress  the value for cust.cust_user_address
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setCustUserAddress(String custUserAddress) {
		this.custUserAddress = custUserAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_user_phone
	 * @return  the value of cust.cust_user_phone
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public String getCustUserPhone() {
		return custUserPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_user_phone
	 * @param custUserPhone  the value for cust.cust_user_phone
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setCustUserPhone(String custUserPhone) {
		this.custUserPhone = custUserPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.cust_date
	 * @return  the value of cust.cust_date
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Date getCustDate() {
		return custDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.cust_date
	 * @param custDate  the value for cust.cust_date
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setCustDate(Date custDate) {
		this.custDate = custDate;
	}
}