package mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CustExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public CustExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCustIdIsNull() {
			addCriterion("cust_id is null");
			return (Criteria) this;
		}

		public Criteria andCustIdIsNotNull() {
			addCriterion("cust_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustIdEqualTo(Integer value) {
			addCriterion("cust_id =", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotEqualTo(Integer value) {
			addCriterion("cust_id <>", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdGreaterThan(Integer value) {
			addCriterion("cust_id >", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("cust_id >=", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdLessThan(Integer value) {
			addCriterion("cust_id <", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdLessThanOrEqualTo(Integer value) {
			addCriterion("cust_id <=", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdIn(List<Integer> values) {
			addCriterion("cust_id in", values, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotIn(List<Integer> values) {
			addCriterion("cust_id not in", values, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdBetween(Integer value1, Integer value2) {
			addCriterion("cust_id between", value1, value2, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotBetween(Integer value1, Integer value2) {
			addCriterion("cust_id not between", value1, value2, "custId");
			return (Criteria) this;
		}

		public Criteria andCustNameIsNull() {
			addCriterion("cust_name is null");
			return (Criteria) this;
		}

		public Criteria andCustNameIsNotNull() {
			addCriterion("cust_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustNameEqualTo(String value) {
			addCriterion("cust_name =", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotEqualTo(String value) {
			addCriterion("cust_name <>", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameGreaterThan(String value) {
			addCriterion("cust_name >", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameGreaterThanOrEqualTo(String value) {
			addCriterion("cust_name >=", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLessThan(String value) {
			addCriterion("cust_name <", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLessThanOrEqualTo(String value) {
			addCriterion("cust_name <=", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLike(String value) {
			addCriterion("cust_name like", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotLike(String value) {
			addCriterion("cust_name not like", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameIn(List<String> values) {
			addCriterion("cust_name in", values, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotIn(List<String> values) {
			addCriterion("cust_name not in", values, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameBetween(String value1, String value2) {
			addCriterion("cust_name between", value1, value2, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotBetween(String value1, String value2) {
			addCriterion("cust_name not between", value1, value2, "custName");
			return (Criteria) this;
		}

		public Criteria andCustCardIsNull() {
			addCriterion("cust_card is null");
			return (Criteria) this;
		}

		public Criteria andCustCardIsNotNull() {
			addCriterion("cust_card is not null");
			return (Criteria) this;
		}

		public Criteria andCustCardEqualTo(String value) {
			addCriterion("cust_card =", value, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardNotEqualTo(String value) {
			addCriterion("cust_card <>", value, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardGreaterThan(String value) {
			addCriterion("cust_card >", value, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardGreaterThanOrEqualTo(String value) {
			addCriterion("cust_card >=", value, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardLessThan(String value) {
			addCriterion("cust_card <", value, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardLessThanOrEqualTo(String value) {
			addCriterion("cust_card <=", value, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardLike(String value) {
			addCriterion("cust_card like", value, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardNotLike(String value) {
			addCriterion("cust_card not like", value, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardIn(List<String> values) {
			addCriterion("cust_card in", values, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardNotIn(List<String> values) {
			addCriterion("cust_card not in", values, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardBetween(String value1, String value2) {
			addCriterion("cust_card between", value1, value2, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustCardNotBetween(String value1, String value2) {
			addCriterion("cust_card not between", value1, value2, "custCard");
			return (Criteria) this;
		}

		public Criteria andCustUserNameIsNull() {
			addCriterion("cust_user_name is null");
			return (Criteria) this;
		}

		public Criteria andCustUserNameIsNotNull() {
			addCriterion("cust_user_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustUserNameEqualTo(String value) {
			addCriterion("cust_user_name =", value, "custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameNotEqualTo(String value) {
			addCriterion("cust_user_name <>", value, "custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameGreaterThan(String value) {
			addCriterion("cust_user_name >", value, "custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("cust_user_name >=", value, "custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameLessThan(String value) {
			addCriterion("cust_user_name <", value, "custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameLessThanOrEqualTo(String value) {
			addCriterion("cust_user_name <=", value, "custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameLike(String value) {
			addCriterion("cust_user_name like", value, "custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameNotLike(String value) {
			addCriterion("cust_user_name not like", value, "custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameIn(List<String> values) {
			addCriterion("cust_user_name in", values, "custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameNotIn(List<String> values) {
			addCriterion("cust_user_name not in", values, "custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameBetween(String value1, String value2) {
			addCriterion("cust_user_name between", value1, value2,
					"custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserNameNotBetween(String value1, String value2) {
			addCriterion("cust_user_name not between", value1, value2,
					"custUserName");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressIsNull() {
			addCriterion("cust_user_address is null");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressIsNotNull() {
			addCriterion("cust_user_address is not null");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressEqualTo(String value) {
			addCriterion("cust_user_address =", value, "custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressNotEqualTo(String value) {
			addCriterion("cust_user_address <>", value, "custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressGreaterThan(String value) {
			addCriterion("cust_user_address >", value, "custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressGreaterThanOrEqualTo(String value) {
			addCriterion("cust_user_address >=", value, "custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressLessThan(String value) {
			addCriterion("cust_user_address <", value, "custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressLessThanOrEqualTo(String value) {
			addCriterion("cust_user_address <=", value, "custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressLike(String value) {
			addCriterion("cust_user_address like", value, "custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressNotLike(String value) {
			addCriterion("cust_user_address not like", value, "custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressIn(List<String> values) {
			addCriterion("cust_user_address in", values, "custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressNotIn(List<String> values) {
			addCriterion("cust_user_address not in", values, "custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressBetween(String value1, String value2) {
			addCriterion("cust_user_address between", value1, value2,
					"custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserAddressNotBetween(String value1,
				String value2) {
			addCriterion("cust_user_address not between", value1, value2,
					"custUserAddress");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneIsNull() {
			addCriterion("cust_user_phone is null");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneIsNotNull() {
			addCriterion("cust_user_phone is not null");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneEqualTo(String value) {
			addCriterion("cust_user_phone =", value, "custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneNotEqualTo(String value) {
			addCriterion("cust_user_phone <>", value, "custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneGreaterThan(String value) {
			addCriterion("cust_user_phone >", value, "custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("cust_user_phone >=", value, "custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneLessThan(String value) {
			addCriterion("cust_user_phone <", value, "custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneLessThanOrEqualTo(String value) {
			addCriterion("cust_user_phone <=", value, "custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneLike(String value) {
			addCriterion("cust_user_phone like", value, "custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneNotLike(String value) {
			addCriterion("cust_user_phone not like", value, "custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneIn(List<String> values) {
			addCriterion("cust_user_phone in", values, "custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneNotIn(List<String> values) {
			addCriterion("cust_user_phone not in", values, "custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneBetween(String value1, String value2) {
			addCriterion("cust_user_phone between", value1, value2,
					"custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustUserPhoneNotBetween(String value1, String value2) {
			addCriterion("cust_user_phone not between", value1, value2,
					"custUserPhone");
			return (Criteria) this;
		}

		public Criteria andCustDateIsNull() {
			addCriterion("cust_date is null");
			return (Criteria) this;
		}

		public Criteria andCustDateIsNotNull() {
			addCriterion("cust_date is not null");
			return (Criteria) this;
		}

		public Criteria andCustDateEqualTo(Date value) {
			addCriterion("cust_date =", value, "custDate");
			return (Criteria) this;
		}

		public Criteria andCustDateNotEqualTo(Date value) {
			addCriterion("cust_date <>", value, "custDate");
			return (Criteria) this;
		}

		public Criteria andCustDateGreaterThan(Date value) {
			addCriterion("cust_date >", value, "custDate");
			return (Criteria) this;
		}

		public Criteria andCustDateGreaterThanOrEqualTo(Date value) {
			addCriterion("cust_date >=", value, "custDate");
			return (Criteria) this;
		}

		public Criteria andCustDateLessThan(Date value) {
			addCriterion("cust_date <", value, "custDate");
			return (Criteria) this;
		}

		public Criteria andCustDateLessThanOrEqualTo(Date value) {
			addCriterion("cust_date <=", value, "custDate");
			return (Criteria) this;
		}

		public Criteria andCustDateIn(List<Date> values) {
			addCriterion("cust_date in", values, "custDate");
			return (Criteria) this;
		}

		public Criteria andCustDateNotIn(List<Date> values) {
			addCriterion("cust_date not in", values, "custDate");
			return (Criteria) this;
		}

		public Criteria andCustDateBetween(Date value1, Date value2) {
			addCriterion("cust_date between", value1, value2, "custDate");
			return (Criteria) this;
		}

		public Criteria andCustDateNotBetween(Date value1, Date value2) {
			addCriterion("cust_date not between", value1, value2, "custDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cust
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cust
     *
     * @mbggenerated do_not_delete_during_merge Mon May 18 19:22:03 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}