package mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProdExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public ProdExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andProdIdIsNull() {
			addCriterion("prod_id is null");
			return (Criteria) this;
		}

		public Criteria andProdIdIsNotNull() {
			addCriterion("prod_id is not null");
			return (Criteria) this;
		}

		public Criteria andProdIdEqualTo(Integer value) {
			addCriterion("prod_id =", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdNotEqualTo(Integer value) {
			addCriterion("prod_id <>", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdGreaterThan(Integer value) {
			addCriterion("prod_id >", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("prod_id >=", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdLessThan(Integer value) {
			addCriterion("prod_id <", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdLessThanOrEqualTo(Integer value) {
			addCriterion("prod_id <=", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdIn(List<Integer> values) {
			addCriterion("prod_id in", values, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdNotIn(List<Integer> values) {
			addCriterion("prod_id not in", values, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdBetween(Integer value1, Integer value2) {
			addCriterion("prod_id between", value1, value2, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdNotBetween(Integer value1, Integer value2) {
			addCriterion("prod_id not between", value1, value2, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdNumberIsNull() {
			addCriterion("prod_number is null");
			return (Criteria) this;
		}

		public Criteria andProdNumberIsNotNull() {
			addCriterion("prod_number is not null");
			return (Criteria) this;
		}

		public Criteria andProdNumberEqualTo(String value) {
			addCriterion("prod_number =", value, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberNotEqualTo(String value) {
			addCriterion("prod_number <>", value, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberGreaterThan(String value) {
			addCriterion("prod_number >", value, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberGreaterThanOrEqualTo(String value) {
			addCriterion("prod_number >=", value, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberLessThan(String value) {
			addCriterion("prod_number <", value, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberLessThanOrEqualTo(String value) {
			addCriterion("prod_number <=", value, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberLike(String value) {
			addCriterion("prod_number like", value, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberNotLike(String value) {
			addCriterion("prod_number not like", value, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberIn(List<String> values) {
			addCriterion("prod_number in", values, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberNotIn(List<String> values) {
			addCriterion("prod_number not in", values, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberBetween(String value1, String value2) {
			addCriterion("prod_number between", value1, value2, "prodNumber");
			return (Criteria) this;
		}

		public Criteria andProdNumberNotBetween(String value1, String value2) {
			addCriterion("prod_number not between", value1, value2,
					"prodNumber");
			return (Criteria) this;
		}

		public Criteria andCustIdIsNull() {
			addCriterion("cust_id is null");
			return (Criteria) this;
		}

		public Criteria andCustIdIsNotNull() {
			addCriterion("cust_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustIdEqualTo(Integer value) {
			addCriterion("cust_id =", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotEqualTo(Integer value) {
			addCriterion("cust_id <>", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdGreaterThan(Integer value) {
			addCriterion("cust_id >", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("cust_id >=", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdLessThan(Integer value) {
			addCriterion("cust_id <", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdLessThanOrEqualTo(Integer value) {
			addCriterion("cust_id <=", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdIn(List<Integer> values) {
			addCriterion("cust_id in", values, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotIn(List<Integer> values) {
			addCriterion("cust_id not in", values, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdBetween(Integer value1, Integer value2) {
			addCriterion("cust_id between", value1, value2, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotBetween(Integer value1, Integer value2) {
			addCriterion("cust_id not between", value1, value2, "custId");
			return (Criteria) this;
		}

		public Criteria andProdHolderIsNull() {
			addCriterion("prod_holder is null");
			return (Criteria) this;
		}

		public Criteria andProdHolderIsNotNull() {
			addCriterion("prod_holder is not null");
			return (Criteria) this;
		}

		public Criteria andProdHolderEqualTo(String value) {
			addCriterion("prod_holder =", value, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderNotEqualTo(String value) {
			addCriterion("prod_holder <>", value, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderGreaterThan(String value) {
			addCriterion("prod_holder >", value, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderGreaterThanOrEqualTo(String value) {
			addCriterion("prod_holder >=", value, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderLessThan(String value) {
			addCriterion("prod_holder <", value, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderLessThanOrEqualTo(String value) {
			addCriterion("prod_holder <=", value, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderLike(String value) {
			addCriterion("prod_holder like", value, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderNotLike(String value) {
			addCriterion("prod_holder not like", value, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderIn(List<String> values) {
			addCriterion("prod_holder in", values, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderNotIn(List<String> values) {
			addCriterion("prod_holder not in", values, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderBetween(String value1, String value2) {
			addCriterion("prod_holder between", value1, value2, "prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdHolderNotBetween(String value1, String value2) {
			addCriterion("prod_holder not between", value1, value2,
					"prodHolder");
			return (Criteria) this;
		}

		public Criteria andProdDateIsNull() {
			addCriterion("prod_date is null");
			return (Criteria) this;
		}

		public Criteria andProdDateIsNotNull() {
			addCriterion("prod_date is not null");
			return (Criteria) this;
		}

		public Criteria andProdDateEqualTo(Date value) {
			addCriterion("prod_date =", value, "prodDate");
			return (Criteria) this;
		}

		public Criteria andProdDateNotEqualTo(Date value) {
			addCriterion("prod_date <>", value, "prodDate");
			return (Criteria) this;
		}

		public Criteria andProdDateGreaterThan(Date value) {
			addCriterion("prod_date >", value, "prodDate");
			return (Criteria) this;
		}

		public Criteria andProdDateGreaterThanOrEqualTo(Date value) {
			addCriterion("prod_date >=", value, "prodDate");
			return (Criteria) this;
		}

		public Criteria andProdDateLessThan(Date value) {
			addCriterion("prod_date <", value, "prodDate");
			return (Criteria) this;
		}

		public Criteria andProdDateLessThanOrEqualTo(Date value) {
			addCriterion("prod_date <=", value, "prodDate");
			return (Criteria) this;
		}

		public Criteria andProdDateIn(List<Date> values) {
			addCriterion("prod_date in", values, "prodDate");
			return (Criteria) this;
		}

		public Criteria andProdDateNotIn(List<Date> values) {
			addCriterion("prod_date not in", values, "prodDate");
			return (Criteria) this;
		}

		public Criteria andProdDateBetween(Date value1, Date value2) {
			addCriterion("prod_date between", value1, value2, "prodDate");
			return (Criteria) this;
		}

		public Criteria andProdDateNotBetween(Date value1, Date value2) {
			addCriterion("prod_date not between", value1, value2, "prodDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table prod
	 * @mbggenerated  Mon May 18 20:23:20 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table prod
     *
     * @mbggenerated do_not_delete_during_merge Mon May 18 19:22:03 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}